sudo: required
services:
  - docker

before_install:
  - docker build -t ksp01/docker-test -f Dockerfile.dev .

script:
  - docker run ksp01/docker-test npm test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-test"
  env: "DockerTest-env"
  bucket_name: "elasticbeanstalk-eu-west-1-474215239256"
  bucket_path: "docker-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

